#!/usr/bin/env bash

day() {
	local y=$1
	local d
	d=$(printf "%02d" "$2")

	local fp="$y/day$d"
	mkdir -p "$fp/assets"
	touch "$fp/assets/input.txt"
	touch "$fp/assets/test.txt"

	echo "$fp"
}

today() {
	local y
	local m
	local d
	y=$(date +"%Y")
	m=$(date +"%m")
	d=$(date +"%d")
	if [[ $m != 12 ]]; then
		echo "today can only be used during December"
		exit 1
	fi
	day "$y" "$d"
}

usage() {
	echo "./aoc [command]"
	echo
	echo "[Commands]"
	echo "today (t): print today's puzzle dir, creating it if needed."
	echo "day (d): print a given day's puzzle dir (provide year (yyyy) and day), creating it if needed."
}

main() {
	case $1 in
	today | t)
		today
		;;
	day | d)
		shift
		day "$@"
		;;
	*)
		usage
		exit 1
		;;
	esac
}

main "$@"
